### PR TITLE
Github Social Media Icon

### PR DESCRIPTION
**Pull request by Atharvp18**
Hey, @adithyapaib I have added a cool CSS animation for the GitHub icon, and added the href link which will direct the user to your GitHub repo!
Thank you

### CODE REVIEW

**Comment by adithyapaib** [comment]
This branch has conflicts that must be resolved
Use the web editor or the  to resolve conflicts.
Conflicting files
index.html

**Comment by Atharvp18** [comment]
Hey, @adithyapaib Now it's showing the branch has no conflicts. Please review

**Comment by Atharvp18** [comment]
I have resolved the conflicts again, please review! @adithyapaib

**Comment by Atharvp18** [comment]
Sorry, by mistake I had closed the pr.

**Comment by adithyapaib** [comment]
This branch has conflicts that must be resolved
Use the web editor or the  to resolve conflicts.
Conflicting files
assets/style.css
index.html

**Pull request closed without merging**
