### PR TITLE
Change calculate new text into a button.

### PR DESCRIPTION
**Pull request by Dcode-k**
Sir, please review my PR and Please merge it if there is not any further correction.

### CODE REVIEW

**Comment by adithyapaib** [comment]
This branch has conflicts that must be resolved
Use the web editor or the  to resolve conflicts.
Conflicting files
assets/index.js
assets/style.css

**Comment by Dcode-k** [comment]
okk sir

**Comment by adithyapaib** [comment]
This branch has conflicts that must be resolved
Use the web editor or the  to resolve conflicts.
Conflicting files
assets/index.js
assets/style.css

**Comment by adithyapaib** [comment]
This branch has conflicts that must be resolved
 to resolve conflicts before continuing.
Conflicting files
assets/index.js

**Pull request closed without merging**
